// Code generated by Kitex v0.8.0. DO NOT EDIT.

package lowerservice

import (
	"context"
	echo "github.com/cloudwego/kitex-tests/thrift_streaming/kitex_gen_cross/echo"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return lowerServiceServiceInfo
}

var lowerServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "lower_service"
	handlerType := (*echo.LowerService)(nil)
	methods := map[string]kitex.MethodInfo{
		"echo_pingPong": kitex.NewMethodInfo(echoPingPongHandler, newLowerServiceEchoPingPongArgs, newLowerServiceEchoPingPongResult, false),
	}
	extra := map[string]interface{}{
		"PackageName":     "echo",
		"ServiceFilePath": `idl/api.thrift`,
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.8.0",
		Extra:           extra,
	}
	return svcInfo
}

func echoPingPongHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*echo.LowerServiceEchoPingPongArgs)
	realResult := result.(*echo.LowerServiceEchoPingPongResult)
	success, err := handler.(echo.LowerService).EchoPingPong(ctx, realArg.Req1)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newLowerServiceEchoPingPongArgs() interface{} {
	return echo.NewLowerServiceEchoPingPongArgs()
}

func newLowerServiceEchoPingPongResult() interface{} {
	return echo.NewLowerServiceEchoPingPongResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) EchoPingPong(ctx context.Context, req1 *echo.LowerRequest) (r *echo.LowerResponse, err error) {
	var _args echo.LowerServiceEchoPingPongArgs
	_args.Req1 = req1
	var _result echo.LowerServiceEchoPingPongResult
	if err = p.c.Call(ctx, "echo_pingPong", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
