// Code generated by Kitex v0.12.3. DO NOT EDIT.

package stservice

import (
	"context"
	instparam "github.com/cloudwego/kitex-tests/kitex_gen_slim/thrift/instparam"
	stability "github.com/cloudwego/kitex-tests/kitex_gen_slim/thrift/stability"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	VisitOneway(ctx context.Context, req *stability.STRequest, callOptions ...callopt.Option) (err error)
	TestSTReq(ctx context.Context, req *stability.STRequest, callOptions ...callopt.Option) (r *stability.STResponse, err error)
	TestObjReq(ctx context.Context, req *instparam.ObjReq, callOptions ...callopt.Option) (r *instparam.ObjResp, err error)
	TestException(ctx context.Context, req *stability.STRequest, callOptions ...callopt.Option) (r *stability.STResponse, err error)
	CircuitBreakTest(ctx context.Context, req *stability.STRequest, callOptions ...callopt.Option) (r *stability.STResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kSTServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kSTServiceClient struct {
	*kClient
}

func (p *kSTServiceClient) VisitOneway(ctx context.Context, req *stability.STRequest, callOptions ...callopt.Option) (err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.VisitOneway(ctx, req)
}

func (p *kSTServiceClient) TestSTReq(ctx context.Context, req *stability.STRequest, callOptions ...callopt.Option) (r *stability.STResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.TestSTReq(ctx, req)
}

func (p *kSTServiceClient) TestObjReq(ctx context.Context, req *instparam.ObjReq, callOptions ...callopt.Option) (r *instparam.ObjResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.TestObjReq(ctx, req)
}

func (p *kSTServiceClient) TestException(ctx context.Context, req *stability.STRequest, callOptions ...callopt.Option) (r *stability.STResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.TestException(ctx, req)
}

func (p *kSTServiceClient) CircuitBreakTest(ctx context.Context, req *stability.STRequest, callOptions ...callopt.Option) (r *stability.STResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CircuitBreakTest(ctx, req)
}
