header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: CloudWeGo Authors

  paths:
    - '**/*.go'
    - '**/*.thrift'
    - '**/*.proto'
    - '**/*.sh'
    - '**/*.s'

  paths-ignore:
    - 'kitex_gen/**/*.go;'
    - 'thrift_streaming/kitex_gen/**/*.go'
    - 'thrift_streaming/kitex_gen_slim/**/*.go'
    - 'thrift_streaming/kitex_gen_old/**/*.go'
    - 'thrift_streaming/kitex_gen_cross/**/*.go'
    - 'thrift_streaming/thrift_slim_amd64_test.go'
    - 'thrift_streaming/thrift_slim_others_test.go'

  comment: on-failure
