// Code generated by thriftgo (0.3.20). DO NOT EDIT.

package multi_service2

import (
	"context"
	"fmt"
)

type Request struct {
	Message string `thrift:"message,1" frugal:"1,default,string" json:"message"`
}

func NewRequest() *Request {
	return &Request{}
}

func (p *Request) InitDefault() {
}

func (p *Request) GetMessage() (v string) {
	return p.Message
}
func (p *Request) SetMessage(val string) {
	p.Message = val
}

func (p *Request) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Request(%+v)", *p)
}

var fieldIDToName_Request = map[int16]string{
	1: "message",
}

type Response struct {
	Message string `thrift:"message,1" frugal:"1,default,string" json:"message"`
}

func NewResponse() *Response {
	return &Response{}
}

func (p *Response) InitDefault() {
}

func (p *Response) GetMessage() (v string) {
	return p.Message
}
func (p *Response) SetMessage(val string) {
	p.Message = val
}

func (p *Response) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Response(%+v)", *p)
}

var fieldIDToName_Response = map[int16]string{
	1: "message",
}

type ServiceA interface {
	EchoA(ctx context.Context, req *Request) (r *Response, err error)
}

type ServiceAEchoAArgs struct {
	Req *Request `thrift:"req,1" frugal:"1,default,Request" json:"req"`
}

func NewServiceAEchoAArgs() *ServiceAEchoAArgs {
	return &ServiceAEchoAArgs{}
}

func (p *ServiceAEchoAArgs) InitDefault() {
}

var ServiceAEchoAArgs_Req_DEFAULT *Request

func (p *ServiceAEchoAArgs) GetReq() (v *Request) {
	if !p.IsSetReq() {
		return ServiceAEchoAArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ServiceAEchoAArgs) SetReq(val *Request) {
	p.Req = val
}

func (p *ServiceAEchoAArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ServiceAEchoAArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ServiceAEchoAArgs(%+v)", *p)
}

var fieldIDToName_ServiceAEchoAArgs = map[int16]string{
	1: "req",
}

type ServiceAEchoAResult struct {
	Success *Response `thrift:"success,0,optional" frugal:"0,optional,Response" json:"success,omitempty"`
}

func NewServiceAEchoAResult() *ServiceAEchoAResult {
	return &ServiceAEchoAResult{}
}

func (p *ServiceAEchoAResult) InitDefault() {
}

var ServiceAEchoAResult_Success_DEFAULT *Response

func (p *ServiceAEchoAResult) GetSuccess() (v *Response) {
	if !p.IsSetSuccess() {
		return ServiceAEchoAResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ServiceAEchoAResult) SetSuccess(x interface{}) {
	p.Success = x.(*Response)
}

func (p *ServiceAEchoAResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ServiceAEchoAResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ServiceAEchoAResult(%+v)", *p)
}

var fieldIDToName_ServiceAEchoAResult = map[int16]string{
	0: "success",
}
