// Code generated by Kitex v0.12.1. DO NOT EDIT.

package servicea

import (
	"context"
	grpc_demo "github.com/cloudwego/kitex-tests/streamx/kitex_gen/protobuf/grpc_demo"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	streamcall "github.com/cloudwego/kitex/client/callopt/streamcall"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	transport "github.com/cloudwego/kitex/transport"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CallUnary(ctx context.Context, Req *grpc_demo.Request, callOptions ...callopt.Option) (r *grpc_demo.Reply, err error)
	CallClientStream(ctx context.Context, callOptions ...streamcall.Option) (stream ServiceA_CallClientStreamClient, err error)
	CallServerStream(ctx context.Context, Req *grpc_demo.Request, callOptions ...streamcall.Option) (stream ServiceA_CallServerStreamClient, err error)
	CallBidiStream(ctx context.Context, callOptions ...streamcall.Option) (stream ServiceA_CallBidiStreamClient, err error)
}

type ServiceA_CallClientStreamClient streaming.ClientStreamingClient[grpc_demo.Request, grpc_demo.Reply]

type ServiceA_CallServerStreamClient streaming.ServerStreamingClient[grpc_demo.Reply]

type ServiceA_CallBidiStreamClient streaming.BidiStreamingClient[grpc_demo.Request, grpc_demo.Reply]

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, client.WithTransportProtocol(transport.GRPC))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kServiceAClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kServiceAClient struct {
	*kClient
}

func (p *kServiceAClient) CallUnary(ctx context.Context, Req *grpc_demo.Request, callOptions ...callopt.Option) (r *grpc_demo.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CallUnary(ctx, Req)
}

func (p *kServiceAClient) CallClientStream(ctx context.Context, callOptions ...streamcall.Option) (stream ServiceA_CallClientStreamClient, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, streamcall.GetCallOptions(callOptions))
	return p.kClient.CallClientStream(ctx)
}

func (p *kServiceAClient) CallServerStream(ctx context.Context, Req *grpc_demo.Request, callOptions ...streamcall.Option) (stream ServiceA_CallServerStreamClient, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, streamcall.GetCallOptions(callOptions))
	return p.kClient.CallServerStream(ctx, Req)
}

func (p *kServiceAClient) CallBidiStream(ctx context.Context, callOptions ...streamcall.Option) (stream ServiceA_CallBidiStreamClient, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, streamcall.GetCallOptions(callOptions))
	return p.kClient.CallBidiStream(ctx)
}
