// Code generated by Kitex v0.5.2. DO NOT EDIT.
package servicea

import (
	unknown_handler "github.com/cloudwego/kitex-tests/kitex_gen/protobuf/unknown_handler"
	server "github.com/cloudwego/kitex/server"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler unknown_handler.ServiceA, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
