// Code generated by Kitex v0.8.0. DO NOT EDIT.

package abcservice

import (
	"context"
	c "github.com/cloudwego/kitex-tests/thrift_streaming/kitex_gen_cross/a/b/c"
	echo "github.com/cloudwego/kitex-tests/thrift_streaming/kitex_gen_cross/echo"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return aBCServiceServiceInfo
}

var aBCServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "ABCService"
	handlerType := (*echo.ABCService)(nil)
	methods := map[string]kitex.MethodInfo{
		"Echo": kitex.NewMethodInfo(echoHandler, newABCServiceEchoArgs, newABCServiceEchoResult, false),
	}
	extra := map[string]interface{}{
		"PackageName":     "echo",
		"ServiceFilePath": `idl/api.thrift`,
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.8.0",
		Extra:           extra,
	}
	return svcInfo
}

func echoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*echo.ABCServiceEchoArgs)
	realResult := result.(*echo.ABCServiceEchoResult)
	success, err := handler.(echo.ABCService).Echo(ctx, realArg.Req1, realArg.Req2)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newABCServiceEchoArgs() interface{} {
	return echo.NewABCServiceEchoArgs()
}

func newABCServiceEchoResult() interface{} {
	return echo.NewABCServiceEchoResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Echo(ctx context.Context, req1 *c.Request, req2 *c.Request) (r *c.Response, err error) {
	var _args echo.ABCServiceEchoArgs
	_args.Req1 = req1
	_args.Req2 = req2
	var _result echo.ABCServiceEchoResult
	if err = p.c.Call(ctx, "Echo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
