// Code generated by Kitex v0.12.1. DO NOT EDIT.

package serviceb

import (
	grpc_demo "github.com/cloudwego/kitex-tests/streamx/kitex_gen/protobuf/grpc_demo"
	server "github.com/cloudwego/kitex/server"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler grpc_demo.ServiceB, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
